language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
# command to install dependencies
install: "pip install ."
# command to run tests
script: nosetests --with-doctest

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0ca6f1a824e3f5200418
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

