title = "TOML Example"
# This is a TOML document.


[owner]
dob = 1979-05-27T07:32:00-08:00
name = "Tom Preston-Werner"

[database]
connection_max = 5000
enabled = true
ports = [ 8001, 8001, 8002 ]
server = "192.168.1.1"

[servers]

  # Indentation (tabs and/or spaces) is allowed but not required


  [servers.alpha]
  dc = "eqdc10"
  ip = "10.0.0.1"

  [servers.beta]
  dc = "eqdc10"
  ip = "10.0.0.2"

[clients]
data = [ ["gamma", "delta"], [1, 2] ]
hosts = [
  "alpha",
  "omega"
]
key3 = """\
       The quick brown \
       fox jumps over \
       the lazy dog.\
       """
lines = '''
The first newline is
trimmed in raw strings.
   All other whitespace
   is preserved.
'''
quoted = 'Tom "Dubs" Preston-Werner'
regex = '<\i\c*\s*>'
regex2 = '''I [dw]on't need \d{2} apples'''
str2 = """
The quick brown \


  fox jumps over \
    the lazy dog."""
str_multiline = """
Roses are red
Violets are blue"""
str_quoted = "I'm a string. \"You can quote me\". Name\tJos\u00E9\nLocation\tSF."
winpath = 'C:\Users\nodejs\templates'
winpath2 = '\\ServerX\admin$\system32\'

[[fruit]]
name = "apple"

  [fruit.physical]
  color = "red"
  shape = "round"

  [[fruit.variety]]
  name = "red delicious"

  [[fruit.variety]]
  name = "granny smith"

[[fruit]]
name = "banana"

  [[fruit.variety]]
  name = "plantain"
  points = [ { x = 1, y = 2, z = 3 },         # This value is so special to me
           { x = 7, y = 8, z = 9 },
           { x = 2, y = 4, z = 8 } ]

